### ISSUE TITLE
Odd animation behaviour on Firefox/Windows.

### ISSUE THREAD

**Issue by natebc** [pac-dev/AmbientGarden#1]
When loading up ambient.garden on Firefox (minimal addons, privacy badger, uBlock Origin) the animation doesn't play at all unless I open and close the ublock origin window which allows the animation to pass frame by frame. see video below.

https://github.com/pac-dev/AmbientGarden/assets/53818/e5fb2ee8-ba0f-4fe5-9ce7-876ca5fad326

console output:
```
Assuming audio can be preloaded before user action. appFrozen.js:3623:3813
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. appFrozen.js:3626:5524
Assuming HTMLAudioElement can play asynchronously. appFrozen.js:3626:5811
preloading patch vib 2 3 + 1 appFrozen.js:3626:8536
preloading patch vib 8 9 + 1 appFrozen.js:3626:8536
preloading patch rdrone 1 4/3 5/3 + 1 appFrozen.js:3626:8536
preloading patch cbass 3/4 + 0.5 appFrozen.js:3626:8536
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. 12 appFrozen.js:3626:7616
playing patch vib 2 3 + 1 appFrozen.js:3626:8953
playing patch rdrone 1 4/3 5/3 + 1 appFrozen.js:3626:8953
```

**Comment by pac-dev** [comment]
Thanks for taking the time. Would you mind trying again? I just pushed a change that caused breakage\* on high-refresh-rate devices. Incidentally, Firefox on Windows with uBlock Origin happens to be my main browser as well, so I'm still not sure how to reproduce the problem.

\*Minor edit: I pushed a change **to fix** breakage on high-refresh-rate devices, lol

**Comment by natebc** [comment]
Hey! It works now. My display is 240Hz so I'm guessing your other fix fixed this issue as well!

/close
